clusters:
  - name : "ocpcluster"
    api_vip: "192.168.122.99"
    ingress_vip: "192.168.122.101"
    kubeconfig: "/root/kubeconfig.ocpcluster"
    version: "4.16.0-nightly"
    network_api_port: "eno12399"
    postconfig:
    - name: "dpu_operator_host"
      dpu_operator_path: "../"
    masters:
    - name: "nicmodecluster-master-1"
      type: "vm"
      node: "localhost"
      ip: "192.168.122.2"
    - name: "nicmodecluster-master-2"
      type: "vm"
      node: "localhost"
      ip: "192.168.122.3"
    - name: "nicmodecluster-master-3"
      type: "vm"
      node: "localhost"
      ip: "192.168.122.4"
    workers:
    - name: "worker-{{worker_number(0)}}"
      type: "physical"
      node: "{{worker_name(0)}}" 
      bmc_user: "root"
      bmc_password: "calvin"
      bmc: "{{bmc(0)}}"
