clusters:
  - name : "iso_cluster"
    api_vip: "192.168.122.99"
    ingress_vip: "192.168.122.101"
    network_api_port: "{{secondary_network_port()}}"
    kind: "iso"
    install_iso: "./RHEL-9.6.0-20250416.8-aarch64-dvd1-w-kickstart.iso"
    masters:
    - name: "{{worker_number(0)}}-acc"
      node: "localhost"
      kind: "dpu"
      bmc:
        url: "{{bmc_hostname(0)}}"
      bmc_host:
        user: "root"
        password: "calvin"
        url: "{{bmc(0)}}"
      dpu_host: "{{worker_name(0)}}"
      ip: "172.16.3.16"
      mac: "{{DPU_mac_address(0)}}"
    preconfig:
    - name: "host_registries"
      import_pull_secret: true
    - name: dpu_firmware
      mev_version: "2.0.0.11126"
    - name: "iso_builder"
      final_iso_name: "./RHEL-9.6.0-20250416.8-aarch64-dvd1-w-kickstart.iso"
      organization_id: "{{organization_id()}}"
      activation_key: "{{activation_key()}}"
    postconfig:
    - name: "dpu_operator_dpu"
      dpu_operator_path: "../../"
